apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp 
  namespace: webapp-ns
spec:
  containers:
  - name: webapp
    image: 396561719560.dkr.ecr.us-east-1.amazonaws.com/webapp-image:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    env:
    - name: DBPWD
      value: "password"
    - name: DBHOST 
      value: "mysql-service.mysql-ns.svc.cluster.local"  
    - name: DBUSER
      value: "root"
    - name: DBPORT
      value: "3306"
    - name: DATABASE
      value: "employees"

        

