apiVersion: apps/v1
kind: Deployment                   # <----- Deployment manifiest for webapp
metadata:
  name: websapp-deployment
  namespace: webapp-ns
spec:
  replicas: 3                     # <----- Replicaset for webapp deployment
  selector:
    matchLabels:
      app: employees 
  template:                       # <----- Pod Manifest for webapp
    metadata:
      labels:
        app: employees 
    spec:
      containers:
      - name: webapp
        image: 396561719560.dkr.ecr.us-east-1.amazonaws.com/webapp-image:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBPWD
          value: "password"
        - name: DBHOST
          value: "IPAddressofMySQLPod"
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPORT
          value: "3306"
 